using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeetCode
{
    internal class _0649_Dota2Senate
    {
        public void Run()
        {
            //Console.WriteLine(PredictPartyVictory("RD"));
            //Console.WriteLine(PredictPartyVictory("RDD"));
            //Console.WriteLine(PredictPartyVictory("DDRRR"));
            //Console.WriteLine(PredictPartyVictory("RRDDD"));


            Console.WriteLine(PredictPartyVictory("DDRDRDDDRRRDRRRRDDRDRDDRRRRRRDRDDRDDRDRRDRRRRRDDRDRRRDRDDDDDDDDDRDRRDRRRDDDRRDRDRDRDDRRRRRRDDRDRDDRDRDDRRDRDRRDDDRDRRDDDRDDRRDRDDRRDDRDDRDRDDRDRRDRDRRDDRRRDRRDDDRDRRDRRRRDDDDRDDRDDDDRRRDRRDRDDRRRDRRDRRDDDDDDDDRDDRRRDDRDRRRDDRDDDRRRDDRDDRDRDDRDDDDRRRRRRDRDDRDRDDRRDRDRRDRRDDRRDDDRRDDDRRDDDDDDRRDRDDDDRRDDDDRRRRRDDDDRRRRDRRDDDDDRRRRRDRDDRDDRRRRDDRRDDRRDDDRRRDRDDDRDDDDRRDDDDDDRRRDRRDDDDDRRRDRDRRDDDDDDDRDDRDRRRDDRRRDRDDRDDRRRDDDRRDRDRDRDRRRDDRDDDRRDRRDDRDRDDRRDRRDDDRDDRDRRDRRDRDRRDDDDDDRDRRRDDRDDDRRRDDDRDRDDDDDRDRRRRRRDRDDRDDDDRDRDRRDRRRDDRRDRDRDRRRDDDRDRDRRRDDRRRRRRDRRRRDDRRRDDRRDDRRRDDDDDRDRDDRRDDRRDDRDDDDRDDRRRRRDDRRRRDRRDRRRDRDDDRDDDRRDDDRRDRDDDDDRDRRRRDRDDRDDDDRDDDRDDDRDDRDRDRRDRDRDDRRRDRRRRDRDRRDRRDDDRRRDRRRRDDRDRDRRRRDDDRRDDRRRRDDDDRRRRDRDDRRRDRRDRDDDRDRRDDRDRDDDRDRRDDDRDRDDRRRDDRRRDDRDDDRRRRDRDDDDDDRRRRRDRRRDRRRRDRRRDRDDDDRRRDRDDDDRRRDRDDRRDRRRRRRDRDRRRDRDDRRDDDDDRRDRRDRRDDRRDRDRDDRDRDDRDDDDDDDDDRDDRDDRDRRRDRRRRDDDDDRDRDDDDRDDDRDDRDRDRDRDDDRDRDDDRRDDRRRDDRRRRDDDDDDDDRDDDDRRDRDRRRRRRDRRRRDRDDDRRDRDRRRDRDRDDRDRRDRRRRRRRDDRDRRRDDDDRRRRRRRRRDDDDRDRRDDDRRDDRDDDDRRRRRRRRRRDDDDRRRRRDDDDDDRRDDDDDRRRDRRDRDRDRDDRRRRDRRDRDDDRDDDDDDDRDDRRDDRRRDRRRDRRDDDDRDRRDRRDRDRDDDRDDDRRRDDRRRRRRDDRDRDRDDDRDDDDDRRDDRDRDRDDDDRDDDRRRRRRDDDRRDDRDDDDDDDDRDRRDDDDDRDDRRRDDDDRDDRDRRDRDDDDRRDRDDDDRDDRRDDDDDDDRDRDRRDDRRDDDRDDRDDDDRDDDRRDRRRDRRDRRDDDDDDRDDDRDDDDDRDRRDDRDDRDDRDRRRRDRRRDRRRRDRRDDDDDDDRRDDRDDDDRDRRRDRDDRDRRRDDRRRDRRRRRRDRRDDDRRRDRRRRRRDDRRDRRDRDRDRDRDRRRDDRDDDDDRRDRRDRRRDRDRDRDRDRRRRDRRRDRRDRRRDRDDRDRRDRRRDRDDRRDRDDDDDRDDRRRDRRDRDDDDRRDDRRRRRRRRRDRRDRDDDRDRRDDRRRRDRDRRRDRRDDRDRRDDRRRDDRDRDRDDRDDRDRDDDRRRDRRDRDDRDDRRRDRDRDRRDRDRDRDRDRRDDRRDDRDRRDRDRDDRRDDDDDRRDRRRDRDDDDDRDRRDRDDDDRRRRDDDDRDRRDRDRDDRDDDDDDRRRRRDRRDDDRDDDDRRDRRDDRDRDDDRRRRRDRDRRDRDRDRDRDRDDRRDRDRDRDDDDRRDDRDDDDRDDDDDDRDDDRDRRDRDDDDDRDDRRRDRRDRRRDRDDDDDDRRDDDRRRDRDDDRRRRRDDDDRRDDDDDDDRDRDDDRDDDDDDDRDDRRDRDRRDDDDDDDDRRRDDRDDDDDRRDDDRRRDRDDDDRRRDRRRRRDRDRDDDRDDRRDRRRRDRRRRRDDDRRDRDRRRRDDRDDDRDRDRRRRRRRRRRRDDDDDRRDRRDDDRDRRRRRDRDRRDDDRRDDDRRRRDRDDDRRDDRDDDDRDDDRDRRDRRRDDRDDDDDRDRRRDRRDRRRDDDRRDRDRDDDDDRDDDDDRDRRDDDDRRDDRRDRDRDRRRRDDRDDDDRRRDDDRDRRDDRDDRRDDRRRRDRRDDDRRDDRRDDRRRDDDDRDRRRDRDRRDDDRRRDDRDDDDRRRDRDDDDRDRDDRDRRRRDRDDDRRDRRDRRRDDRRDDRDRDRRDRDRDRDDRRDDDRRRRRDDDRDDRDRRRRRRRDRDDRRRDDRRRRRDRDRDDDDDDDDRDDRRRRDDRRDDDDDDDRRDRDDRDRRDDRRDDRDDRDDDRDDRRDRRRRRDRRDDRRRDDRRDDDDRDRDRDRDRRRRRDRDRDRDDRDRRRDRRDDRRDRRDDRDRDDDDRDRDRRDRDRDDDDRDDRDDDDRRDRRDDRDRDRRDRDDRRDRDDRRRDDDDRRDDDDRRRRDRRRDDDRDRRDDRDRDRRDRRRRRRRDDRDDRRRDDRRDRRRDRDRDRDDRRDDRRRDRRRDDRDDRDDRDRDRDDRRDRRRRRDRDDDRDRDDRDDDRRDDDDRRDRRRRDRRRDDRDDDDDRRDDDRRRRRRRRDRRDRRRRRRRRDRRRDDDRDRDDRDRDDDRRDRRDDDRDDRDRDRRDRDDDDDDDDDRRRRRDRRRDRDRRDRDRDRRRDDDRDRRDRRRDDRDDRDRDRRRDRRRDDDRRDRDDDDDRDDRRRRRDRRDRDRRRDRDRDDRDDDRDRRRDDDDDDDDDRRDRDRRRRRDDRDDDDRRRRRRDRRDDRDDRDDRDDRDDRRRDRRRRDRRDDRRDDRDDRDRDDDRDRDRRRDDRDRRDRRDDDDDRDDRDDRRRRDRRDRDRDDRRDRDRRRDDDRDRDDDRRDRDDDRDRDRRRDRRRRDRDRRRDDDRRDRDRDDRDRDRRRDRRDDDRDRRDDRRRRDRRDRDDDRDDRRRRDDDDRRDRDRDDDRDDRRRDDRRDDRRDRRRDRRDRDRDDRDDRRDRRRDRDRRRRDRRRRDDDRRDRRRDRDDRDRDDRDRRDRRDRRDRRRRRDRRRDRRRRDDDRDRDDDRDRRRRRDDDRRDDRRDDRDRRDRDRDRDDRDRDRRRDRDRRDDRDDRRRRRRDRRDRDDDRDRRRDDRRRRDDRRRRDDDDRDRDRRRDRRDRRDDRRRDDRDRDDDDDDDRRRDDDDRDRRDRRDRDRRRDRRRRDRRRDDDRRRDDDDRDRRDDRDDRDDRRDDDRRRRRDRRDRDDRDDDRDRRRRDRRDRDRRDRDDDDRRRDDDDDRRDDDDRRDRRDDDDRDRDDRRDDRRRRRRDDDDRDRRDRDDDRDDRRDRRRDRRDRRDDDDRDRRDRDDDRRRDDDRRRRRDDRDDRRDDDRDDRDRRRRRRRDRRRDRDRDRRDRDRRRRRRDDRDRDRDRRDDRRRRDDRRDDRRRDDDDDRDRDDRDDRRDDDRRDDDRRDRDRRRRRRRRRDRDRRRRRDDDRRDRRRRDRRDRRDRRDRDDRRDRDRRRDRDRDDDRRDRRDRRDDDRRDRRDRDRDDRRDRRRDRDDRRRDDDDRDDRRDRRRDDRRDRDRRDDRRRRDRRDRRDDRDRRRDDDRRRDRDDDDDDRDRDDRDRDRRDDRRDRRRDRDDRDDRRRRRRRRDRRDDDDDRDRRDDRRRRRDDRDDRRDRRRRRRDRRDDRRRRDRRDRDDRRDRRRRRDDRDDRDRRDDRDRRDDDRDRRDDDRDRDRRRRRRRDRRDDRRRRDDDRRDRDDRRDDRDRDRRDDRRDDRDRDRDRRRRDRDDRDDRDRRRRDDRDRRRRRRRDRDDDRDRDDRDDRDRDRDRDDDRRRDRRDRRDRRDDRRRRRDRDDRDDRRRRRRRRDRRRRRRRRRRRDRDRRRRRRDRDRRRDRDRRDDDDRRRRRDRRDRDDRDDRDDDRRDRRDRDRRDRDDDDDDRRDDRDDRRDRDRRRDDDDDRDRRDDRDRDDRDRDRDDRDDRRDRRRRDRRRDDDRRDRRDRDRRDDRDDRDDDDRDDDDRRRRDDDRDDRDDDDDDDDRDRRDRDDDDRDDDDRRRRRDDRDRDDRRDRRDRDRRDRDDRRDRDRRDDRDRDRDRRRRRDRDRDDRDDDDRRRRRDDRRRRDRRDRDRDDDRDDRDDRRRRDRRRDRRDRDDDDRDDRDRRRRDDDRRDRRDRRDRDDRDRRDRRDRDDRRRRDDRRRDRDRRDRRDRRDDDRRRRDRDDDRRRDRDRRDRDDDRRRRDDRDRRRRDDRDRRRDRRRRRDRRDDDDDRRRDRDDRRRDDRDDDRRDDRDRDDRDRDRRRRDDRRDRRDRDRDRRDDRRDDRDRDRDDDRDRDRRRDRDRDRRDDRDRDDDRDDRRRRRRDDRDRRRRDDRDRDDDRRDDDDDRDRDDRRDRDDRRDDDRDRDDDRRDDDDDRDRDRDDRDDDRRRDDDDRRRDRRRRRDRDRRDRRDDDRRDRDRRDDDRDDRDDDDDRDDDDRDDDDRDDDDDDDRRDRRRDRDDDRDRDRDDDRDDRDRDRRDDDDRRRRRRRDRRRRRDRDRRRRDDRRDRDDRDRDRDRDRDDDDDDDRDRDRRDDDDDDRRRDRRDRRDRRRRDDRRDRDRRRDRDRRDDDRDRDRDRRRDRRDRDDDDDDRRRRDDDDDDRDDDRRDDDRDDRDDDDDDRRDRDDDDDRRRRDRRRDDRRRDRRRDRDRDDRRDRRRRDDRRDRRRRRRRRDDRDRDRRRDRRDDDDDDDRDDRRRDRDRRRDRDDDRDRDRDRRDRDDRDRDRRDDRDDRRDDDRRDDDRRRRRDDRDDDRDRRRRDRRDDDDDRRDRRRDRDRDDRRRRDRDDDRRRRRRDRRRDDRDRDRDRRDDRDRRRDRRRRDDRRDDRDDDRDRRRRRRDRRDRRRRDRRRRDRRDRRDRDRRDDDRRRDRDDRRRRDRRRDRDRRRRRRDDDDDDDDRRDDRDDDRDDDDRDRRDDRDRDRRDDRDRDDRRDDRDDRRRRDDDRRDDRRDDDRDDDDDRRRRDDRRRDDDDRDDRDRDDRDRDRDDRRDRRDDRDRDDDDRRRRRDRRRDRDDRDDRRDDRDRDDDDRRDRDRRDRRRDRDDDDRRDRDRDRDRRDRRDRDRRDRDDRRDDDDRRRRRRDRDRRDDRRDRRDRDDRRRDRDDRDDRDRDRRRRRRDDRRRDRRRDRDDDRRDRRDDRRDDRDRRDDDDDDDRRRRRRRRDRRRRRRDDRRDDRRRRDDRRRDRDDRDDRDDDDRRRDRRRDRDRDRRRRRRDDRRDRDRDRRRRDRDDDDRDDDRDDDDRDRDDRDRDDDRDDRRDRRRRRDRDRDDDRRDRDRRRDDRRRRDRRRDDRDDDDDRDRRRDDDDDDDDRDDDRRDDRRDRRDRDDDDDDRRDRRRDDDDDDDDRRRRRRRRRRDRRDDRDRDDRRDRDDRDRRRDDDRRRRDDRRRDRDRDRRRDRRDRDDRRDDRRRDDDRRRDRRDRRRRDRDDRRRRDRRRDDRDDDDRRDDRDRRDDDDRDDDRDDRRDDDDDRRDRDDDDRDDDDRRRDDDRRDDRDDRDRRRRDRRDRRRRRRDDRDRRDRDDDRDDDRRRRRRDRRRDRRDRRRDDRDRRRDRRDRDDRRRRDRDDRRDRRDDRRRDRDDRDRDDDRDRRDRDDDRDRDRDRDRDDDRRDRDDDDRRRDDRDDRRRDRDDDRRDDRRDRRRRRRDDDDDRRDRDRDDDRDDDRDRRDRDRRRRDDRDRDRDRRRRRDDDRDDRRDDDRRDRRDDRRRRDDRRRDDRRDRDRDRDRRRDDDDDDRRDRDDRRRRDRRRRRDRDDDDRRDRDRRRDRDRDRRDRRRRRDDDDRRDRDDRRDRRRDDRDDRRRRDDDDDRRRDRDDRRDDRRDRDDDRRRDRRDRDDRRDRDRDRRRDDRDRRDDRRRRRDDRDRDDRDDRDDRDDRDRRDDDDRRDRDDDDRRDDDDDRDDRRRDDRDRRRDDRRRDRRRRRRDRRDDRDDRRDRDRDDDDDRRRRDRRDRDDRRRDDDRDDRRDDDDDDRDRDDDDRDRDRDRDDRDRRDDRRRRRDRRDRRDDRDDRRDDRRDRRRRRRRRDDDRRDRRDRDDRRDRDDRRDRRRDDRDDDDDDDRDRRDRRRRDDDDRRDRRDDRRRRRRDRDDRDRDRDDRDRRDRDDDRRDDRDDRDDDDDDRDRRRRDDRDRDRRDRDRRDDRRDDDDRDDDDRRDRRRRDDRRDRDDRRDDRRDDDRDRDRRDDDDDDDDRDDDDRDRDDRDDRRDRRRDDDRRDDRRDDRRRDRDRRDDRDDDDRDRRDRDDDDDRDRRRRDDRRRRDDDRRDRRRDRDRDDRRRRRDDRRRRDRDDDRDRRRRRRDDDDDDRRDRRDRDRDDDDDRDDDDDRRRRDRDRDRDRDDDRDRRDDRDRRDDRRRDDDDDDRRRDRDRRRRDDDDDDRDRRDDRRRDRRDDRRRRDRDDRRRRDRRRRRRDDDDRRRRDDDRDDRDRDRDDRDRRRRRDDDRDDDDDRRRDRDDRRRRRRRDRRDDRRDDRRDDDDDRRRDDDRDRRRRRDRRDDDRDDDDRRRDDDRDDRDDRDDDRDDRDRRRRDDDRRDRDDDRRRDDRDDRRRRDRDRRDDRDDRDRRDDRDRDRDDRRDDDRRRRDDDDRRDDRRRDDRDDRDDRRDDDRDRRRDDRDRRDRRDRDDDRRRRRRRDRRDRDDRRDDDDDRRDDRRRRRRDDDDDDDRRDRDDRDDRRRDRDDRDDDDDRRRDRRDRRRRDRDDRRDDRRDRDDRDRDRRRDRRRRDRRDDDRDRRDRRRRDDDDRRDRRRDDRRDDRRRRDDRDDRDDRDRRDRDDRRRDDRRRDDRRDDDDRRDRDRRRDRDDRRDDRRDRRDRRDRRRRRDDRDRDDRDDRRDRDRRDDDRDRRDDDRDDDRDRRRDDDDDDDRRDDRDDDRRDRRDRRRDDRDDRDRDDRRDDRDRDRRDRRDRDDDDRRRDDRDDDDDRDRDRRRRDRRDDDRDRRRRDRRRRRRRDRDDDDDDDRDDDDDRDDRRDDRRDRDDDRRRDDRRDDDDDDRDRRRDRDRRRRRRDRDDRDRDRDRRRDDRDRDDDDDRDRRRRDDDDRDRDDRRDDDRDRRRRRRDDRDDRDDDRDDRRDRDRRDDRDRRDDDRRDDRDDDDDRRDDRDRDRDDRRDDRRRDRDRRDDRRRRRRRRRRDRDDDRDDRRRDRDRRDDDRDRRRDDRDDRDDDDDRDDDDRRDDRRRDRRRRRDRDRRDDRRDRDDDDDDRDRDRRDDDDDDDDDRRRRDRDRRRRRRDDRRRDDRRRDRDRDDRDDDDRDDRRDDRDDRRDRDDRRDRRDRRDRDRRRDDRDRDDRRRDDDRDDDDDRDDDDRDRDRDDRRDRDDRRDRRRRDRDDRDRRRDDRRDRDDDRRDRRRRRRDDRDDDRRDRDRRDRDDDDRRDRRRDDRDDDRDRDDDRDRRRDDRRRDRRRRRRDRDRRRRRRDRDRRDRDRDDDRRDRDDRRRDRDRDRRDRDDDRRRDDRDRDRRRDDRRRDDRRDRRRRDDDDRRRDDDDDRRRDRRRRRDRDDRRRDRDRRRRRDRRDRDDDDRDDDDRDRRDRDDDRDRDRRRDRDDRRDDDRDRDRDRRRRDRRRDDRRDRDRRRDRRDRRRRRDRRDRRRDDDDRRDDRDRDDDRRDDDDRDRDDRDDRDDDDRRRRDDDDDRRDDDRDDDRDRDRRRRDDDDDDDRRRRDRDRRDRDRDDDRRRRDRRDDRDDDDRDRDDDRRRDRRRDRRRDDRRRDRDDRDRRRRRRDDRRDRDRRDRRDDRRDRRDDDRDRRDRDRDRDDDRDRRDDRDRDRDDDDDDDRRRDDRRDRRDDRRRDRDDDRDDDDRRRRRRDDRRDDRRRRDDDDRDRRDRRRRDDRDDRDDRRRRDRDDRDRRRRRRRRDRRRRRRRRDDRRRDRDDRDDDRRDDDRRRRRRRRDDRRDRRDRDRRRDRRDRRRRDRDDDRRRRDDDRRRRRRRRDRRRDRRDRDRDRDDDDDRRRRDDDDRRRRRDDRDRDRDRDDDRRRDDRRRDDRRRDDRRDDRRRRRRDDDRRRDRRRRRDRDDDDRDDRRRRRRRDRDDRRRRDDDRRRRRRDDRDRRRRDRRRRDDDDDDRRRDRRDRDRDDRRDDDDRDRDRRRRRDDRRDDRRDRRDDRRRRRDDDDDRRDRDDRDDDRDDDRRDDRRDRRDDDRDDDDDRRRRRDDDDRDRRRDDRDRDDRRDRRRDRDDDRRDRRDDRDDRDRRRDDDRDDRRRRRRRRDDDDDDRRRDDDRRDDRDRDDRRDRDRRRDDDDRDDRDRRRDDRRDDDDRRDDRDRRRDRRDDDDRDDRRRRRDRRRRRRRRRRDDRRDRRDDRDDRDRRRRDDDDDDRDDDRRDDRRDDDDRRRDRDRRDRRRRDDRDRRDRDDRRDRRRRDDDDRRRRDDRDDDDDRDDRRDRDDDRDRRRDRDRDRDRDDDRRDDDDRDRDRDRRDRDRRDDRDDRRDDDDRDDRRDRRDRDRDRDRDDRRDDDRDDRRRRDDRDDRDDRDDDDRDDRRDDDDDDRDRRRDRDRRRRRDRRDDDRRDDRDRDDDRRDDRDRRRRDDDDDRRRDRDDRRRRRDRDRRDRDRDDRDRRRDDRRRDRDRDDRDRRDDRDRRDDRDDRDDRDRRRDDDRDRRRRRRRRDDRRDRRRDDDDDDDDDRRRRRDRRRRRRDRRRDDDRRDRDRDRRDRRDDDRDDRRRDDDRDDDDRDRRRRDDDRRRDDDDRDRRRDRRRRDDDRRDRRRDDRRRDDDRDDRDDDRDRRDRRRRRRRRRDDRDRDRRRDDRRDRDRRRRRDRRDRDRRDRDRDRDDRRDRDRDDRRDDDRRDRRDDDRRDDRDRDDDDRRDRRDDDDRDDRRRRDDDRRDDDRRRDDDRDDRRDRDRRDRRDDDRDDRRDRRDDDDDRRRRRDDRDRRRRRRRRDRRDRRRRRRRDDRDRDDRDRDDDRDDRDRRDRDDRRDDRDDDDRDRDDDDDRDRRRRDDDRDDDDRDDRRDRDDRRDRDRRDDDRRRRRDDDDDDDRRDRRDDRRRRDRDRRDDRRDDRRDDRRDRDRDRRDDRDDDDDDRDDRDRDRRRRDDRRDDRRDDRDDRDRRDRRRDDRDRDDRDRDRRDRDDRDDRRDRRRDDRDRDRDDRDDRDDRDRRDRRRDRRDRDDDDDDDDRRDDDDDDRDDRDDDDDDRDDDDRDRRDDRDDRDDDRRRDDRRRRDDRDDDDRDDRDRDDDRDRRRDRRRRDDDRRRDRDDRRRDRRRDDRDRDDDRRRDRRRRRDDRRRRDRRRDDRRDDDDDDDRRDDDDRDDRRDRDDRRDRDDDDRDRRRDRRDRDRRDDRRDDRDRDRDRRDDRRRRDDRDDDRDDRRDRDRRRRRRDDRDDRRDDRDDRDRRDDDDDDDRRDDRDRRRDRDDDRRDDRRDRRDDDRRRDRRRDDDRDRRRDRRDRDDDDRDRRRRDRDDRRRRRDDRRDDDRDRRRRRDRDRRDDRRRRRRDRDRDDRRDDDRDDDRDRDDRRRDDDDRRRRDRRRDDRDRRRRDRRDDRDDRDDDRRRRDDRRRDRRDRRRRDDDDDRDDRRRDRDDRRRRRDDRDDRRDRDRDRRDRRDRRRDDDDRRDDRRDDDRDDRRRDDRDRRRDDRRDRRDRDDDDDDRRDRDDRDRDRDDRRDDRDDDDDDRRDRRDDRDDDDDDDRDRRDRDDRDDRRRDDDRRDRRDRRDDDDRDDRDDDDDDRDRRDRRDRDRDDDDRDDDDRDDRDDRRRDRDRRDDDRDDDDDRDRDDRRDRRRDRDRRDRDDDDDDRRRDDDDDRDDRRRRRDDRRRDRDRRRDDDDDDRDDRDDDDDRDRRDRRRDRDDDRDRRRDRRRRDRRRDRDDDDDRDDDRRRDRDDRRRDDDDDRDRRRRRRDRRDRDRRDDDRRDDDRDDRDRRDDDRRDDRDDDDDDDRRRRRDRDDRRRDRRDRRDRDRRDDDRDRDDDDRDDRDDRDDDRDDRRRRDRRDRRRRDRDDRDRRDDRRRDDDDRRRRDRRDRDRDDRDRDRRRRDDRDRDDDDRRRRDRDDDRRRDRRRRDDRRRDRR"));


            // DDXRR
            // DDXXR
            // DDXXR
            // DDXXR
            // XDXXR
            // XDXXX

        }
        public string PredictPartyVictory(string senate)
        {
            bool winner = false;
            var q = new Queue<char>(senate);
            var rEncountered = 0;
            var dEncountered = 0;

            int rCount = q.Count(x => x == 'R');
            int dCount = q.Count(y => y == 'D');

            while (!winner)
            {
                char c = q.Peek();

                //if (c == 'R' && q.Count(x => x == 'D') == 0)
                //{
                //    return "Radiant";
                //}
                //else if (c == 'D' && q.Count(x => x == 'R') == 0)
                //{
                //    return "Dire";
                //}

                if (c == 'R' && rCount > 0 && dCount == 0)
                {
                    return "Radiant";
                }
                else if (c == 'D' && dCount > 0 && rCount == 0)
                {
                    return "Dire";
                }

                if (c == 'R')
                {
                    q.Dequeue();

                    if (dEncountered > 0)
                    {
                        dEncountered--;
                        rCount--;
                    }
                    else
                    {
                        q.Enqueue(c);
                        rEncountered++;
                    }
                }
                else // if (c == 'D')
                {
                    q.Dequeue();

                    if (rEncountered > 0)
                    {
                        rEncountered--;
                        dCount--;
                    }
                    else
                    {
                        q.Enqueue(c);
                        dEncountered++;
                    }
                }
            }

            throw new ArgumentOutOfRangeException();
        }
    }
}
